version: '3.9'
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: LeiRecords
    ports:
      - "18001:27017"
    volumes:
      - mongo-volume:/data/db
  leiapi:
    build: .
    environment:
      USE_SWAGGER : TRUE
    ports:
      - "8001:80"
  reverseproxy:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
      - 443:443
volumes:
  mongo-volume: